---
- name: Install Ruby and Bundler
  hosts: all
  become: true

  roles:
    - app

#  tasks:
#  - name: Install a list of packages
#    apt: 
#      name: ['ruby-full', 'ruby-bundler', 'build-essential']
#      state: present

